
### API 1 scenario-1
GET http://localhost:3000/todos/?status=TO%20DO

### API 1 scenario-2
GET http://localhost:3000/todos/?priority=HIGH

### API 1 scenario-3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

### API 1 scenario-4
GET http://localhost:3000/todos/?search_q=Buy

### API 1 scenario-5
GET http://localhost:3000/todos/?category=WORK&status=DONE

### API 1 scenario-6
GET http://localhost:3000/todos/?category=HOME

### API 1 scenario-7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH


### API 2 no need check
GET http://localhost:3000/todos/6/

### API 3 checked
GET http://localhost:3000/agenda/?date=2021-02-22

### API 4 checked
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 9,
  "todo": "Uttej test",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

### API 5 scenario - 1 checked
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "status": "DONE"
}

### API 5 scenario - 2 checked
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "priority": "HIGH"
}


### API 5 scenario - 3 no need check
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "todo": "Clean the garden"
}


### API 5 scenario - 4 checked
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "category": "LEARNING"
}


### API 5 scenario - 5 checked
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "dueDate": "2021-01-12"
}

### API 6
DELETE http://localhost:3000/todos/6/




### test
GET http://localhost:3000/alltodos/